title = "Rafael R. Silva | CyberSecurity"
theme = "PaperMod"

[params]
env = "production"
title = "Rafael R. Silva"
description = "Offensive Security, Vulnerability Research & SecOps"

# Força o tema escuro por padrão
defaultTheme = "dark"
disableThemeToggle = false

# Recursos extras nos posts
showShareButtons = true
showCodeCopyButtons = true
ShowReadingTime = true

# ==============================================================================
# 1. REDES SOCIAIS 
# ==============================================================================

[[params.socialIcons]]
name = "github"
url = "https://github.com/Rafa314"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/rafael-dos-reis-silva-849a3b249/"

[[params.socialIcons]]
name = "email"
url = "mailto:rei42782@gmail.com"

# ==============================================================================
# 2. MODO PERFIL 
# ==============================================================================

[params.profileMode]
enabled = true
title = "Rafael dos Reis Silva"
subtitle = "Information Security Analyst | Red Team & Vulnerability Management"
imageUrl = "images/rafael2.png" 
imageTitle = "Rafael R. Silva"
imageWidth = 190
imageHeight = 190

[[params.profileMode.buttons]]
name = "Blog & Writeups"
url = "/posts/"

[[params.profileMode.buttons]]
name = "GitHub Portfolio"
url = "https://github.com/Rafa314"

[[params.profileMode.buttons]]
name = "Currículo"
url = "/docs/RAFAEL_REIS_CURRICULO.pdf"

# ==============================================================================
# 3. MENUS DE NAVEGAÇÃO
# ==============================================================================

[menu]
[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
name = "Projetos"   
url = "/projects/"
weight = 15

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
name = "Sobre Mim"
url = "/about/"
weight = 30
